In [8]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np


In [10]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Special Arrays
np.zeros((3, 3))
np.ones((2, 4))
np.eye(3)
np.arange(0, 10, 2)
np.linspace(0, 1, 5)
np.random.rand(3, 2)
np.random.randn(3, 2)

array([[ 0.9084077 ,  0.55036266],
       [ 1.69967535,  1.91458361],
       [-1.21587139, -0.29890212]])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


In [12]:
# Basic Math
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b
a * b
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [13]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [14]:
arr = np.array([1, 2, 3, 4])
arr.sum()
arr.mean()
arr.max()
arr.min()
arr.std()

np.float64(1.118033988749895)

In [15]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]
arr[1:4]
arr[::2]

array([1, 3, 5])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]
arr[:, 1]
arr[1, :2]

array([4, 5])

In [18]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [20]:
arr = np.arange(6)
arr.reshape(2, 3)

# Concatenation
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [21]:
np.vstack((a, b))
np.hstack((a, b))

array([1, 2, 3, 4])

In [22]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [25]:
np.save('array.npy', arr)

# Load from a file
loaded_arr = np.load('array.npy')